version: "3"

services:
  video-broadcast-api:
    build: .
    tty: true
    ports:
      - 9000:9000
      - 5005:5005
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/.ivy2:/root/.ivy2"
      - ".:/opt/video-broadcast-api"
      - "/opt/video-broadcast-api/target"
      - "/opt/video-broadcast-api/project/target"
      - "/root/.sbt/1.0/plugins"
    environment:
      POSTGRESQL_URL: "jdbc:postgresql://postgres-database:5432/video-broadcast-api"
      POSTGRESQL_USER: "user"
      POSTGRESQL_PASSWORD: "password"

  postgres-database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "video-broadcast-api"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"

